
import { observable } from 'https://unpkg.com/mobx@5.x?module'

export const patternsStore = observable({
  currentPattern: 'chakras',
  patternData: {
    chakras: {
      label: 'Chakras',
      colors: {
        'C': '#EC472D',
        'C#': '#EC5F2D',
        'D': '#EC972D',
        'D#': '#F6AB0B',
        'E': '#F6D70B',
        'F': '#40C070',
        'F#': '#40C0AD',
        'G': '#0080FF',
        'G#': '#1369EB',
        'A': '#204ADA',
        'A#': '#5C22ED',
        'B': '#9D32F5',
      },
    },
    chromesthesia: {
      label: 'Chromesthesia',
      colors: {
        'C': '#B2B9CD',
        'C#': '#8D3B4C',
        'D': '#E1BF5C',
        'D#': '#BA64E1',
        'E': '#3793B4',
        'F': '#A0A883',
        'F#': '#69B777',
        'G': '#F56A4E',
        'G#': '#8B2F64',
        'A': '#EC9F40',
        'A#': '#D3BD8D',
        'B': '#D3BED9',
      },
    },
    emotion: {
      label: 'Emotion',
      colors: {
        'C': '#0E74D9',
        'C#': '#4BB0FF',
        'D': '#C80006',
        'D#': '#0F7102',
        'E': '#17AA05',
        'F': '#FD6809',
        'F#': '#3F31FF',
        'G': '#0000BD',
        'G#': '#FC0007',
        'A': '#FFE744',
        'A#': '#FFFF43',
        'B': '#D400D6',
      },
    },
    chromotherapy: {
      label: 'Chromotherapy',
      colors: {
        'C': '#46680e',
        'C#': '#4a996b',
        'D': '#23778f',
        'D#': '#2c3358',
        'E': '#e37081',
        'F': '#934682',
        'F#': '#40C0AD',
        'G': '#fc5719',
        'G#': '#a43a11',
        'A': '#fd7d0f',
        'A#': '#fd9f18',
        'B': '#fdb217',
      },
    },
    adolescence: {
      label: 'Adolescence',
      colors: {
        'C': '#E2CF0B',
        'C#': '#FFE50C',
        'D': '#35C80B',
        'D#': '#0B33A5',
        'E': '#19BDA2',
        'F': '#835BD9',
        'F#': '#774ACB',
        'G': '#E4C5DD',
        'G#': '#E0BFD7',
        'A': '#A30008',
        'A#': '#9B1A6F',
        'B': '#BA000A',
      },
    },
    custom: {
      label: 'Custom',
      colors: {
        'C': '#E2CF0B',
        'C#': '#FFE50C',
        'D': '#35C80B',
        'D#': '#0B33A5',
        'E': '#19BDA2',
        'F': '#835BD9',
        'F#': '#774ACB',
        'G': '#E4C5DD',
        'G#': '#E0BFD7',
        'A': '#A30008',
        'A#': '#9B1A6F',
        'B': '#BA000A',
      },
    }
  },
  notes: ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'],
})
